# Generated by Django 5.0 on 2024-01-07 22:19

from django.db import migrations, models
from datetime import date  # Import the date class

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_photo_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city_town',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(default=date(2000, 1, 1)),  # Set a proper default date
            preserve_default=False,
        ),
    ]
