# Generated by Django 5.0 on 2024-01-08 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_course_profile_module_s1_profile_module_s2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='module_s1',
            new_name='module_Selection_1',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='module_s2',
            new_name='module_Selection_2',
        ),
    ]
