# Generated by Django 5.0 on 2024-01-08 00:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduleregistrationsystem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='course',
        ),
        migrations.AddField(
            model_name='module',
            name='availability',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10),
        ),
        migrations.AddField(
            model_name='module',
            name='category',
            field=models.CharField(default='null', max_length=100, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AddField(
            model_name='module',
            name='code',
            field=models.CharField(default='null', max_length=20, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AddField(
            model_name='module',
            name='courses_allowed',
            field=models.CharField(choices=[('comp', 'Computing'), ('bio_sci', 'Biomedical Science'), ('edu', 'Education')], default='null', max_length=10, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AddField(
            model_name='module',
            name='credit',
            field=models.IntegerField(default='60'),
        ),
        migrations.AlterField(
            model_name='module',
            name='description',
            field=models.TextField(default='null', validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(default='null', max_length=255, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
