# Generated by Django 5.0 on 2024-01-08 04:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduleregistrationsystem', '0003_module_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='availability',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='open', max_length=10),
        ),
        migrations.AlterField(
            model_name='module',
            name='courses_allowed',
            field=models.CharField(choices=[('Computing', 'Computing'), ('Biomedical Science', 'Biomedical Science'), ('Education', 'Education')], default='null', max_length=20, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
